[package]
  name = "rust"
  version = "0.1.0"
  edition = "2024"

[dependencies]
  bitcoincore-rpc = "0.18"
  bitcoin = "0.32"
  serde = { version = "1", features = ["derive"] }
  serde_json = "1.0"
  thiserror = "2"
